// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a_emory_survery_api.Dal;

#nullable disable

namespace a_emory_survery_api.Migrations
{
    [DbContext(typeof(EmorySurveyDbContext))]
    [Migration("20220324194731_seedQuestions")]
    partial class seedQuestions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("a_emory_survery_api.Dal.QuestionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionDefinition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Question 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Question 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Question 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Question 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Question 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
